# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to Npm packages

on:
  release:
    types: [created]

jobs:
  publish-npm:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
        working-directory: packages/vuefer
      - run: yarn build
        working-directory: packages/vuefer
      - run: npm publish --access public
        working-directory: packages/vuefer
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE}}
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - run: yarn install
  #       - run: npm test
